---
- name: Validate required variables
  assert:
    that:
      - docker_key_url is defined
      - docker_key_path is defined
      - dkrs_packages is defined
    fail_msg: "Required variable is not defined."

- name: Ensure the keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Check if Docker GPG key is already imported
  ansible.builtin.stat:
    path: "{{ docker_key_path }}"
  register: gpg_key

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_key_url }}"
    dest: /tmp/docker.gpg
    mode: '0644'
  when: not gpg_key.stat.exists

- name: Import Docker GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o {{ docker_key_path }} /tmp/docker.gpg
    creates: "{{ docker_key_path }}"
  notify: "update cache"
  when: not gpg_key.stat.exists

- name: Set permissions for Docker GPG key
  ansible.builtin.file:
    path: "{{ docker_key_path }}"
    mode: '0644'
    state: file
  when: not gpg_key.stat.exists

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_key_path }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  notify: "update cache"

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ dkrs_packages }}"

- name: Ensure a non_root_user is in the 'docker' group
  ansible.builtin.user:
    name: "{{ non_root_user }}"
    groups: docker
    append: yes
